Members frontend
tasera-ry/tss pull request #115
Opened 2021-11-10 10:33 UTC by II-KA

Add frontend for viewing and editing members

Created this just for a peer review, not merging till members-backend is complete.

Don't be fooled by the '17,508 additions and 16,870 deletions', the amount of changes is due to 'Add color definitions to frontend' commit 😅

2021-11-11 11:57 UTC, II-KA commented
- Updated the translations

If anyone can think of a better term for "gun licence owners" feel free to suggest

2021-11-11 14:06 UTC, II-KA commented
Added the 'in raffle' checkbox to the table (and it can be updated)

2021-11-16 09:05 UTC, pkangasmaki requested changes
Erittäin hyvää duunia, näyttää tosi hyvältä 👍 Kommentoin pienen huomion !importanttien käytöstä.

Laittaisin muuten vielä pienen marginin tuon koko taulukon alle, niin ei sivu lopu heti kun taulukkokin loppuu. Antaisi selkeämmin kuvan, että nyt päästiin loppuun. Tällä hetkellä siis sivuston ihan alas rullatessa näyttää tältä (musta osuus on siis windowsin alapalkki):
![image](https://user-images.githubusercontent.com/60352215/141954803-8f22a7e7-765c-4bb7-905f-09a516708c3c.png).

Jos löytyy aikaa ja jaksamista, niin myös taulukon solujen järjestely painamalla taulukon otsikkoa voisi olla mukava lisäys. Mutta se on oletettavasti aikaa vievä prosessi, niin tän voisi jättää backlogiin odotteleen, kunnes saat tehtyä muut tärkeämmän prioriteetin hommat alta pois. (ellei sitten oo suuri halu tehä heti, en estä tietty 😄)

2021-11-16 11:51 UTC, II-KA commented on front/src/raffle/usersTable.module.scss
> +}
Sain iconButtonit ilman `!important` määrittelyä lisäämällä `path` css-selectoriin. En nyt ainakaan heti keksinyt miten saman saisi aikaan checkboxille

2021-11-16 11:55 UTC, II-KA commented
Kiitos erittäin hyvistä huomioista!
- margin lisätty

Luulen että sorttauksen lisäämiseen menisi paljon aikaa eikä tuottaisi hirveästi lisäarvoa. Keskityn ainakin alkuun muihin hommiin 👍

2021-11-16 12:22 UTC, pkangasmaki approved these changes

2021-11-24 13:29 UTC, closed without merging