Login page fixes
tasera-ry/tss pull request #134
Opened 2021-12-09 08:44 UTC by pkangasmaki

Vaihdoin Login ja 'unohditko salasanasi' -sivujen ulkoasua vastaamaan sovelluksen muuta teemaa. Korjasin myös bugin, jossa takaisin näppäin sivuilla ohjasi selaimen historian edelliselle sivulle. Nyt näppäimet ohjaavat:

- Login -> weekview
- Reset password -> Login

2021-12-09 18:31 UTC, II-KA requested changes
Näyttää nätiltä 👍 yksi pieni huomio löyty

2021-12-09 19:11 UTC, pkangasmaki commented on front/src/resetPW/ResetPassword.js
> +});
Alunperin otin tuon värin colors modulesta (löytyy valmiina `COLOR_GREY` jo), mutta se kaatoi testit :sweat_smile: Commit -sivulla näkyy kuinka kolmannen commitin kohalla testit epäonnistui ja virheviestinä tulee:

```
const theme = createMuiTheme({
  palette: {
    primary: {
      main: colors.grey,
    },
  },
});
```

_Material-UI: Unsupported `grey` color.
We support the following formats: #nnn, #nnnnnn, rgb(), rgba(), hsl(), hsla()._

Ja sit kun vaihto nelos-commitissa hex codeiks niin toimi normaalisti. Hyvin kummallista, mutta en tähän hätään löytänyt muuta ratkasua tilanteeseen. Sama myös tuossa toisessa huomiossa, tuntu että kaikki esimerkit ja muitten tekeleet oli aina tehty makeStyles / createMuiTheme / vastaavilla, eikä mistään löytynyt kuinka määritellä ne scss tiedostossa niin päädyin sitten tähän ratkasuun. Onko sulla tullut vastaan miten sais tuon teeman määritellyn järkevästi pois komponentin filun sisältä ja siirrettyä scss filuun?

2021-12-09 20:27 UTC, II-KA commented on front/src/resetPW/ResetPassword.js
> +});
Pitääpä tsiigata tarkemmin huomenna. Vois testata ainakin josko `${colors.grey}` auttais asiaan

2021-12-10 09:42 UTC, II-KA commented on front/src/resetPW/ResetPassword.js
> +});
Päivityksenä en löytänyt ratkaisua testiongelmaan
Jos tietäisi täsmälleen mihin tyyleihin haluaisi tuon colors.grey:n vaikuttavan, niin scss:n puolelta varmaan saisi overridattua - mutta voi vaatia paljon selvittelyä ja varmasti priossa on tärkeämpiäkin asioita

2021-12-10 09:44 UTC, II-KA approved these changes

2021-12-15 07:29 UTC, merged