Feature fr10 banner for supervisors
tasera-ry/tss pull request #17
Opened 2020-10-21 15:44 UTC by Liljenmaa

A banner will show whenever a logged-in user has status "not confirmed" on some of their supervisions.

The banner will disappear if:
- The user clicks on it

The banner will reappear when:
- The user clicks on the TASERA logo
- The user refreshes the page (by the means of F5, changing the language)

The banner will NOT reappear when:
- Other actions mentioned before
- The user performs an action that does not refresh the page (browse weekview, click on the side bar options)

NOTE: Additional testing is useful. If you encounter anything that works oddly or something should work differently, please let me know.

2020-10-23 06:22 UTC, TuoLuo994 commented
I think the banner should stay visible at all times (not disappear when clicked, only when accepted/refused supervision), because confirming the supervision is a high priority task for the user, and even if the user doesn't want to do it right away, the alert-component is not too distracting.

2020-10-23 06:24 UTC, TuoLuo994 commented
With the original background coloring, the current info-severity warning is not visible enough. I would add `variant="filled"` and  change the severity to warning or even error.

2020-10-23 07:45 UTC, Liljenmaa commented on front/src/navbar/Nav.js
> +class SupervisorNotification extends Component {
Done

2020-10-23 09:16 UTC, TuoLuo994 requested changes
If I click on the banner and click cancel, the banner becomes unclickable.

2020-10-27 11:48 UTC, Liljenmaa commented
Fixed the old reservations bug. PR requested.

2020-10-27 18:04 UTC, TuoLuo994 approved these changes

2020-10-27 18:04 UTC, TuoLuo994 commented
Looks good to me

2020-10-27 18:04 UTC, merged