Ol #tw29
tasera-ry/tss pull request #259
Opened 2024-11-05 08:42 UTC by oonaleivo

Rivinvaihtojen tallennus toteutettu. Tähän liittyen uusi UI muutos tarpeen!
Lisätty character limit (255 merkkiä) eli ei anna käyttäjän kirjoittaa sitä enempää tekstikenttään. näin tuota tallennuksen epäonnistumista liian pitkän tekstin takia ei voi enää tulla.

2024-11-05 12:46 UTC, nymank requested changes

2024-11-05 12:46 UTC, nymank commented on front/src/trackview/Trackview.js
> +        <div style={{whiteSpace: 'pre-wrap'}}>
It would be better to not use inline styling. Add a fitting className, and then add css rule in Trackview.module.scss.

2024-11-05 16:56 UTC, nymank approved these changes
Good job

2024-11-08 11:54 UTC, oonaleivo commented
Merging #tw29 fixes.

2024-11-08 11:54 UTC, merged